# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996aeea18700f35ed6f22df32b4a9398b093df4a9483a8896f2ab6328a72a0af816746dee442ec807e3c341e20bf4e3b6ea79011e60e1b00ea450e4bd06b611f

test:
  secret_key_base: 8aeb0ec16efb149f2f3b84aacb7630325639f9c5aa26c7955512445a618b4ed3b06fdad870a75f1b5b25934e765a97cadd3009db541803df45c318386394a8c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
